version: '2'
services:
  eoysky-mysql:
    build:
      context: ./base/config/src/main/resources/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: eoysky-mysql
    image: eoysky-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306

  eoysky-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: eoysky-redis

#  其他模块打包